import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
const modules=new Map();
function load(path){if(modules.has(path))return modules.get(path).exports;const module={exports:{}};modules.set(path,module);vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,URL,URLSearchParams,require:id=>load(id.replace("@/","")+".ts")});return module.exports;}
const cadence=load("lib/growthOutreach.ts"),backfill=load("lib/linkedinCadenceBackfill.ts"),queue=load("lib/linkedinOutreach.ts"),governor=load("lib/operationalGovernor.ts");
const org="tenant-a",first="2026-08-01T12:34:56.000Z",day=n=>Date.parse(first)+n*86400000;
const receipt=(at,message,stage)=>({key:"key-"+at,actor:"operator",evidence:"Explicit actual manual send",completed_at:at,confirmed_at:at,sent_at:at,historical_send_date_status:"verified",message,stage});
function fixture(){return {acquisition_items:[],inbox_items:[{id:"accept",organisation_id:org,platform:"linkedin",kind:"connection_accepted",linkedin_identity:"linkedin.com/in/person",author_name:"Person",created_at_platform:"2026-07-01",status:"replied",response_state:"waiting_for_human",contacted_at:first,last_replied_at:first,last_reply_text:"Original hello exactly",manual_completion:receipt(first,"Original hello exactly","connection")}],growth_targets:[{id:"target",organisation_id:org,linkedin_identity:"linkedin.com/in/person",target_name:"Person",stage:"day3_dm",status:"active",last_action_at:first,manual_completion:receipt(first,"Original hello exactly","connection")}]};}
test("all due dates are absolute from first confirmed send, not latest send",()=>{for(const [stage,n] of Object.entries(cadence.cadenceDays)){if(!n)continue;assert.equal(cadence.growthFollowUpDueAt({stage,manual_completion:receipt(first,"Original","connection"),first_outbound_at:first,last_action_at:"2026-09-15"}),new Date(day(n)).toISOString());}assert.equal(cadence.growthFollowUpDueAt({stage:"day28_relevance",last_action_at:first}),null);});
test("existing contacts jump only to current due stage, preserve evidence, and wait on days zero to two",()=>{for(const [n,stage] of [[0,"day3_followup"],[2,"day3_followup"],[3,"day3_followup"],[6,"day3_followup"],[7,"day7_parity"],[13,"day7_parity"],[14,"day14_insight"],[27,"day14_insight"],[28,"day28_relevance"],[41,"day28_relevance"],[42,"day42_close"],[100,"day42_close"]]){const input=fixture(),before=JSON.stringify(input),report=backfill.planLinkedInCadenceBackfill(org,input,day(n));const target=report.projected.growth_targets[0];assert.equal(target.stage,stage);assert.equal(target.first_outbound_at,first);assert.equal(target.first_outbound_text,"Original hello exactly");assert.equal(JSON.stringify(input),before);assert.equal(target.last_action_at,first);assert.equal(target.manual_completion.message,"Original hello exactly");assert.equal(cadence.isGrowthTargetDue(target,day(n)),n>=3);}});
test("a recorded follow-up is never repeated; next due is still anchored to first send",()=>{const input=fixture();Object.assign(input.growth_targets[0],{stage:"day7_parity",last_action_at:new Date(day(5)).toISOString(),manual_completion:{...receipt(new Date(day(5)).toISOString(),"Actual Day 3 question","day3_followup"),history:[receipt(first,"Original hello exactly","connection")]}});const report=backfill.planLinkedInCadenceBackfill(org,input,day(6));assert.equal(report.projected.growth_targets[0].stage,"day7_parity");assert.equal(cadence.isGrowthTargetDue(report.projected.growth_targets[0],day(6)),false);});
test("genuine replies and stronger states stop backfill and silent cadence",()=>{for(const fields of [{reply_status:"neutral",replied_at:new Date(day(2)).toISOString()},{deal_stage:"meeting"},{deal_stage:"lost"},{deal_stage:"converted"},{status:"parked",stage:"parked"}]){const input=fixture();Object.assign(input.growth_targets[0],fields);const report=backfill.planLinkedInCadenceBackfill(org,input,day(42));assert.equal(report.repairs.length,0);assert.equal(cadence.isGrowthTargetDue(input.growth_targets[0],day(42)),false);}});
test("missing first-send text/time or unverified connection never fabricates history",()=>{for(const damage of [input=>{delete input.inbox_items[0].manual_completion;delete input.inbox_items[0].last_reply_text;delete input.growth_targets[0].manual_completion;},input=>{input.inbox_items=[];}]){const input=fixture();damage(input);assert.equal(backfill.planLinkedInCadenceBackfill(org,input,day(42)).repairs.length,0);}});
test("Follow-ups queue uses actual latest outbound while absolute first timestamp remains unchanged",()=>{const input=fixture();const target=input.growth_targets[0];target.last_action_at=new Date(day(4)).toISOString();target.manual_completion={...receipt(target.last_action_at,"Actual earlier question","day3_followup"),history:[receipt(first,"Original hello exactly","connection")]};target.stage="day7_parity";const projected=backfill.planLinkedInCadenceBackfill(org,input,day(14)).projected;const item=queue.linkedInOutreachQueue(org,projected,day(14),"followups").items[0];assert.ok(item);assert.equal(item.stage,"day14_insight");assert.equal(item.previousOutbound.message,"Actual earlier question");assert.equal(projected.growth_targets[0].first_outbound_at,first);});
test("tenant-specific fallback and stage intent contain no inherited sender facts",()=>{for(const [name,description] of [["A Clinic","grief counselling"],["B Practice","sports rehabilitation"]]){const profile={business:{name,description}};const text=cadence.contextualOutreachDraft({target_name:"Person",stage:"day28_relevance",previous_outbound_text:"Actual question"},profile);assert.match(text,new RegExp(description));assert.doesNotMatch(text,/Root|David|workplace wellbeing|brochure/);assert.doesNotMatch(text,new RegExp(name==="A Clinic"?"sports rehabilitation":"grief counselling"));}assert.equal(cadence.contextualOutreachDraft({target_name:"Person",stage:"day3_followup"},{business:{}}),"");});
test("confirmed final close plans parked exactly once",()=>{const projected=backfill.planLinkedInCadenceBackfill(org,fixture(),day(42)).projected;const plan=governor.planManualCompletion(org,projected,"growth_targets","target");assert.equal(plan.allowed,true);assert.equal(plan.patch.stage,"parked");assert.equal(plan.patch.status,"parked");assert.equal(cadence.nextGrowthStage("day42_close"),"parked");});
test("backfill is tenant isolated and second dry run is idempotent",()=>{const input=fixture();input.growth_targets.push({...input.growth_targets[0],id:"foreign",organisation_id:"tenant-b"});const firstRun=backfill.planLinkedInCadenceBackfill(org,input,day(28));assert.equal(firstRun.repairs.length,1);assert.equal(firstRun.projected.growth_targets[1].stage,"day3_dm");assert.equal(backfill.planLinkedInCadenceBackfill(org,firstRun.projected,day(28)).repairs.length,0);});

test("missing targets are planned for one-time creation without phantom actionable ids",()=>{const input=fixture();input.growth_targets=[];const result=backfill.planLinkedInCadenceBackfill(org,input,day(28));assert.equal(result.repairs[0].id,null);assert.equal(result.repairs[0].patch.stage,"day28_relevance");assert.equal(result.repairs[0].patch.first_outbound_at,first);assert.equal(result.projected.growth_targets.length,0);});
test("a stored stage alone never fabricates intermediate sends or advances the evidence floor",()=>{const input=fixture();input.growth_targets[0].stage="day42_close";const result=backfill.planLinkedInCadenceBackfill(org,input,day(3));assert.equal(result.projected.growth_targets[0].stage,"day3_followup");assert.equal(result.projected.growth_targets[0].manual_completion.stage,"connection");});

const sendEvidence=load("lib/linkedinSendEvidence.ts");
test("actual deployed receipt has confirmation evidence but no verified external send date",()=>{const input=fixture();delete input.inbox_items[0].manual_completion;input.inbox_items[0].status="needs_reply";input.inbox_items[0].response_state="needs_reply";delete input.inbox_items[0].contacted_at;delete input.inbox_items[0].last_replied_at;input.inbox_items[0].source_engine="root_health_b2b";const r=input.growth_targets[0].manual_completion;delete r.stage;delete r.sent_at;delete r.historical_send_date_status;r.history=[];const result=backfill.planLinkedInCadenceBackfill(org,input,day(0));assert.equal(result.excluded.actual_send_unverified,1);assert.equal(result.counts.waiting_day3,0);assert.equal(result.review.length,1);assert.equal(result.repairs.length,0);assert.equal(queue.linkedInOutreachQueue(org,result.projected,day(50)).items.length,0);});
test("confirmed_at and legacy first_outbound_at never drive cadence",()=>{const r=receipt(first,"Exact","connection");delete r.sent_at;delete r.historical_send_date_status;assert.equal(cadence.growthFollowUpDueAt({stage:"day3_followup",first_outbound_at:first,manual_completion:{...r,confirmed_at:first}}),null);});
test("historical correction preserves original receipt and uses old send time",()=>{const input=fixture();const original={key:"old",actor:"operator",evidence:"Confirmed",message:"Original hello exactly",completed_at:new Date(day(18)).toISOString(),history:[]};input.growth_targets[0].manual_completion={...receipt(first,original.message,"connection"),confirmed_at:original.completed_at,correction_type:"first_send_classification",history:[original]};const before=JSON.stringify(input);const result=backfill.planLinkedInCadenceBackfill(org,input,day(18));assert.equal(result.counts.day14_insight,1);assert.equal(result.projected.growth_targets[0].first_outbound_at,first);assert.equal(JSON.stringify(input),before);assert.equal(result.projected.growth_targets[0].manual_completion.history[0].completed_at,original.completed_at);});
test("unknown historical send blocks cadence and duplicate first message",()=>{const input=fixture();input.growth_targets[0].manual_completion={...receipt(first,"Historical exact text","connection"),sent_at:null,historical_send_date_status:"unknown",correction_type:"first_send_classification"};const result=backfill.planLinkedInCadenceBackfill(org,input,day(42));assert.equal(result.excluded.historical_unknown,1);assert.equal(result.repairs.length,0);assert.equal(cadence.isGrowthTargetDue(input.growth_targets[0],day(42)),false);assert.equal(queue.linkedInOutreachQueue(org,result.projected,day(42)).items.length,0);});
test("Sent now and historical evidence separate the two clocks; exact text is preserved",()=>{const body={key:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",confirmed:true,message:"  Exact historical text\n",sendChoice:"now"};const current=sendEvidence.validateSendInput(body,day(18));assert.equal(current.sentAt,current.confirmedAt);assert.equal(current.message,body.message);const historical=sendEvidence.validateSendInput({...body,sendChoice:"historical",sentAt:first,timezone:"Europe/London",timeKnown:true},day(18));assert.equal(historical.sentAt,first);assert.equal(historical.confirmedAt,new Date(day(18)).toISOString());assert.notEqual(historical.sentAt,historical.confirmedAt);assert.equal(historical.source,"Manually reconciled from LinkedIn history");});
test("timezone conversion preserves real historical date and handles date-only precision",()=>{assert.equal(sendEvidence.localSendDate("2026-10-09","12:00","Europe/London"),"2026-10-09T11:00:00.000Z");assert.equal(sendEvidence.localSendDate("2026-01-09","12:00","Europe/London"),"2026-01-09T12:00:00.000Z");assert.equal(sendEvidence.localSendDate("2026-10-09","","Europe/London"),"2026-10-08T23:00:00.000Z");assert.throws(()=>sendEvidence.localSendDate("2026-03-29","01:30","Europe/London"),/does not exist/);});

test("28 real-shaped target receipts remain unverified and never enter Waiting for Day 3",()=>{const data={acquisition_items:[],inbox_items:[],growth_targets:[]};for(let i=0;i<28;i++){const f=fixture(),identity="linkedin.com/in/person-"+i;Object.assign(f.inbox_items[0],{id:"accept-"+i,linkedin_identity:identity,status:"needs_reply",response_state:"needs_reply",source_engine:"root_health_b2b",manual_completion:null,contacted_at:null,last_replied_at:null,last_reply_text:null});const r={key:"receipt-"+i,actor:"operator",evidence:"User explicitly confirmed sending this message manually in LinkedIn via Mark sent & next.",message:"Exact original "+i,completed_at:first,history:[]};Object.assign(f.growth_targets[0],{id:"target-"+i,linkedin_identity:identity,manual_completion:r,source_type:"lifecycle_connection_accepted",source_record_id:"accept-"+i});data.inbox_items.push(...f.inbox_items);data.growth_targets.push(...f.growth_targets);}const report=backfill.planLinkedInCadenceBackfill(org,data,day(0));assert.equal(report.excluded.actual_send_unverified,28);assert.equal(report.review.length,28);assert.equal(report.counts.waiting_day3,0);assert.equal(report.repairs.length,0);assert.equal(queue.linkedInOutreachQueue(org,report.projected,day(60)).items.length,0);});

test("reconciliation source files use valid UTF-8 for Preview builds",()=>{for(const file of ["lib/linkedinCadenceBackfill.ts","app/dashboard/growth/cadence-report/page.tsx","app/dashboard/growth/cadence-report/SendDateReview.tsx","app/dashboard/responses/linkedin/LinkedInHistoricalSend.tsx"]){assert.doesNotThrow(()=>new TextDecoder("utf-8",{fatal:true}).decode(fs.readFileSync(file)));}});

test("conversation history preserves multiple messages and LinkedIn UI text without parsing dates",()=>{const message="  Yesterday\nView profile\nHi there\nToday 8:38 AM\n👏 👍 😊\nAnother outbound\n";const body={key:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",confirmed:true,message,sendChoice:"conversation",dateKnown:false,timezone:"Europe/London"};const details=sendEvidence.validateSendInput(body,day(35));assert.equal(details.message,message);assert.equal(details.sentAt,null);assert.equal(details.status,"unknown");assert.equal(details.contentKind,"conversation_history_pasted");const input=fixture();input.growth_targets[0].manual_completion={...receipt(first,message,"connection"),content_kind:details.contentKind,sent_at:null,historical_send_date_status:"unknown"};const result=backfill.planLinkedInCadenceBackfill(org,input,day(35));assert.equal(result.excluded.historical_unknown,1);assert.equal(result.repairs.length,0);assert.equal(queue.linkedInOutreachQueue(org,result.projected,day(35)).items.length,0);});
test("conversation cadence uses only explicitly confirmed earliest outbound date",()=>{const body={key:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",confirmed:true,message:"Today\nFirst message\nLast week\nFollow-up\nView profile",sendChoice:"conversation",dateKnown:true,sentAt:first,timezone:"Europe/London"};assert.throws(()=>sendEvidence.validateSendInput(body,day(35)),/Explicitly confirm/);const details=sendEvidence.validateSendInput({...body,earliestOutboundConfirmed:true},day(35));assert.equal(details.sentAt,first);const input=fixture();input.growth_targets[0].manual_completion={...receipt(first,body.message,"connection"),content_kind:details.contentKind,correction_type:"first_send_classification",confirmed_at:new Date(day(35)).toISOString()};const report=backfill.planLinkedInCadenceBackfill(org,input,day(35));assert.equal(report.counts.day28_relevance,1);assert.equal(report.projected.growth_targets[0].first_outbound_text,body.message);assert.equal(report.projected.growth_targets[0].manual_completion.history,undefined);});

test("follow-up context labels conversation anchor without dating every pasted message",()=>{const input=fixture();const trail="Yesterday\nFirst outbound\nView profile\nAnother outbound";input.growth_targets[0].manual_completion={...receipt(first,trail,"connection"),content_kind:"conversation_history_pasted"};const projected=backfill.planLinkedInCadenceBackfill(org,input,day(35)).projected;const item=queue.linkedInOutreachQueue(org,projected,day(35),"followups").items[0];assert.ok(item);assert.equal(item.previousOutbound.message,trail);assert.equal(item.previousOutbound.contentKind,"conversation_history_pasted");assert.match(JSON.stringify(item.context.history),/Earliest user-verified outbound date only/);assert.doesNotMatch(JSON.stringify(item.context.history),/Confirmed sent at/);});

const conversation=load("lib/linkedinConversation.ts");
test("conversation messages preserve direction/exact text and never infer unknown dates",()=>{const message="  Today 8:38 AM\nView profile\nReply text\n";const body={key:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",direction:"inbound",message,confirmed:true,dateKnown:false};const entry=conversation.validateConversationMessage(body,day(35));assert.equal(entry.message,message);assert.equal(entry.messageAt,null);assert.equal(entry.source,"manually reconciled from LinkedIn conversation");assert.equal(entry.dateStatus,"unknown");assert.throws(()=>conversation.validateConversationMessage({...body,direction:"sideways"},day(35)));assert.throws(()=>conversation.validateConversationMessage({...body,dateKnown:true},day(35)));});
test("chronological audit keeps every entry, with unknown dates separately in recording order",()=>{const rows=[{id:"c",message_at:null,confirmed_at:"2026-10-03",message:"Unknown"},{id:"b",message_at:"2026-09-02",confirmed_at:"2026-10-01",message:"Second"},{id:"a",message_at:"2026-09-01",confirmed_at:"2026-10-05",message:"First"}];const before=JSON.stringify(rows);const result=conversation.chronologicalMessages(rows);assert.equal(result.dated.map(r=>r.message).join(","),"First,Second");assert.equal(result.undated.length,1);assert.equal(JSON.stringify(rows),before);});
test("inbound conversation flag immediately stops cadence and moves contact to active conversation",()=>{const input=fixture();input.growth_targets[0].linkedin_conversation_active=true;const result=backfill.planLinkedInCadenceBackfill(org,input,day(35));assert.equal(result.excluded.replies,1);assert.equal(result.repairs.length,0);assert.equal(cadence.isGrowthTargetDue(input.growth_targets[0],day(35)),false);assert.equal(queue.linkedInOutreachQueue(org,input,day(35)).items.length,0);const lifecycle=load("lib/contactLifecycle.ts");assert.equal(lifecycle.buildContactLifecycle(org,input,day(35))[0].currentStage,"engaged");input.growth_targets[0].deal_stage="meeting";assert.equal(lifecycle.buildContactLifecycle(org,input,day(35))[0].currentStage,"meeting");});
test("outbound message with unknown date preserves contacted state and prevents a new first message",()=>{const input=fixture();delete input.growth_targets[0].manual_completion;input.growth_targets[0].stage="connection";input.growth_targets[0].last_action_at=null;input.growth_targets[0].linkedin_previously_contacted=true;input.inbox_items[0].manual_completion=null;input.inbox_items[0].last_reply_text=null;input.inbox_items[0].contacted_at=null;input.inbox_items[0].last_replied_at=null;input.inbox_items[0].status="needs_reply";input.inbox_items[0].response_state="needs_reply";assert.equal(cadence.isGrowthTargetDue(input.growth_targets[0],day(35)),false);assert.equal(queue.linkedInOutreachQueue(org,input,day(35)).items.length,0);});

test("full conversation snapshot preserves text and only accepts explicitly confirmed earliest date",()=>{const thread="  Name\nYesterday 8:30\n👏\nView profile\nReply\n";const body={key:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",message:thread,containsInboundReply:true};const snapshot=conversation.validateConversationHistory(body,day(35));assert.equal(snapshot.message,thread);assert.equal(snapshot.earliestOutboundAt,null);assert.equal(snapshot.containsInboundReply,true);assert.throws(()=>conversation.validateConversationHistory({...body,earliestOutboundAt:first,timezone:"Europe/London"},day(35)),/Explicitly confirm/);assert.equal(conversation.validateConversationHistory({...body,earliestOutboundAt:first,earliestOutboundConfirmed:true,timezone:"Europe/London"},day(35)).earliestOutboundAt,first);});
test("snapshot anchor supports cadence without overwriting or preferring it over verified original receipts",()=>{const input=fixture(),original=input.growth_targets[0].manual_completion;input.growth_targets[0].linkedin_cadence_anchor={...receipt(new Date(day(5)).toISOString(),"Full snapshot","connection"),content_kind:"conversation_history_pasted"};assert.equal(cadence.firstConfirmedOutboundAt(input.growth_targets[0]),first);delete original.sent_at;delete original.historical_send_date_status;assert.equal(cadence.firstConfirmedOutboundAt(input.growth_targets[0]),new Date(day(5)).toISOString());assert.equal(original.message,"Original hello exactly");});
