import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
const modules=new Map();
function load(path){if(modules.has(path))return modules.get(path).exports;const module={exports:{}};modules.set(path,module);vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,URL,URLSearchParams,require:id=>load(id.replace("@/","")+".ts")});return module.exports;}
const cadence=load("lib/growthOutreach.ts"),backfill=load("lib/linkedinCadenceBackfill.ts"),queue=load("lib/linkedinOutreach.ts"),governor=load("lib/operationalGovernor.ts");
const org="tenant-a",first="2026-08-01T12:34:56.000Z",day=n=>Date.parse(first)+n*86400000;
const receipt=(at,message,stage)=>({key:"key-"+at,actor:"operator",evidence:"Explicit actual manual send",completed_at:at,message,stage});
function fixture(){return {acquisition_items:[],inbox_items:[{id:"accept",organisation_id:org,platform:"linkedin",kind:"connection_accepted",linkedin_identity:"linkedin.com/in/person",author_name:"Person",created_at_platform:"2026-07-01",status:"replied",response_state:"waiting_for_human",contacted_at:first,last_replied_at:first,last_reply_text:"Original hello exactly",manual_completion:receipt(first,"Original hello exactly","connection")}],growth_targets:[{id:"target",organisation_id:org,linkedin_identity:"linkedin.com/in/person",target_name:"Person",stage:"day3_dm",status:"active",last_action_at:first,manual_completion:receipt(first,"Original hello exactly","connection")}]};}
test("all due dates are absolute from first confirmed send, not latest send",()=>{for(const [stage,n] of Object.entries(cadence.cadenceDays)){if(!n)continue;assert.equal(cadence.growthFollowUpDueAt({stage,first_outbound_at:first,last_action_at:"2026-09-15"}),new Date(day(n)).toISOString());}assert.equal(cadence.growthFollowUpDueAt({stage:"day28_relevance",last_action_at:first}),null);});
test("existing contacts jump only to current due stage, preserve evidence, and wait on days zero to two",()=>{for(const [n,stage] of [[0,"day3_followup"],[2,"day3_followup"],[3,"day3_followup"],[6,"day3_followup"],[7,"day7_parity"],[13,"day7_parity"],[14,"day14_insight"],[27,"day14_insight"],[28,"day28_relevance"],[41,"day28_relevance"],[42,"day42_close"],[100,"day42_close"]]){const input=fixture(),before=JSON.stringify(input),report=backfill.planLinkedInCadenceBackfill(org,input,day(n));const target=report.projected.growth_targets[0];assert.equal(target.stage,stage);assert.equal(target.first_outbound_at,first);assert.equal(target.first_outbound_text,"Original hello exactly");assert.equal(JSON.stringify(input),before);assert.equal(target.last_action_at,first);assert.equal(target.manual_completion.message,"Original hello exactly");assert.equal(cadence.isGrowthTargetDue(target,day(n)),n>=3);}});
test("a recorded follow-up is never repeated; next due is still anchored to first send",()=>{const input=fixture();Object.assign(input.growth_targets[0],{stage:"day7_parity",last_action_at:new Date(day(5)).toISOString(),manual_completion:receipt(new Date(day(5)).toISOString(),"Actual Day 3 question","day3_followup")});const report=backfill.planLinkedInCadenceBackfill(org,input,day(6));assert.equal(report.projected.growth_targets[0].stage,"day7_parity");assert.equal(cadence.isGrowthTargetDue(report.projected.growth_targets[0],day(6)),false);});
test("genuine replies and stronger states stop backfill and silent cadence",()=>{for(const fields of [{reply_status:"neutral",replied_at:new Date(day(2)).toISOString()},{deal_stage:"meeting"},{deal_stage:"lost"},{deal_stage:"converted"},{status:"parked",stage:"parked"}]){const input=fixture();Object.assign(input.growth_targets[0],fields);const report=backfill.planLinkedInCadenceBackfill(org,input,day(42));assert.equal(report.repairs.length,0);assert.equal(cadence.isGrowthTargetDue(input.growth_targets[0],day(42)),false);}});
test("missing first-send text/time or unverified connection never fabricates history",()=>{for(const damage of [input=>{delete input.inbox_items[0].manual_completion;delete input.inbox_items[0].last_reply_text;delete input.growth_targets[0].manual_completion;},input=>{input.inbox_items=[];}]){const input=fixture();damage(input);assert.equal(backfill.planLinkedInCadenceBackfill(org,input,day(42)).repairs.length,0);}});
test("Follow-ups queue uses actual latest outbound while absolute first timestamp remains unchanged",()=>{const input=fixture();const target=input.growth_targets[0];target.last_action_at=new Date(day(4)).toISOString();target.manual_completion=receipt(target.last_action_at,"Actual earlier question","day3_followup");target.stage="day7_parity";const projected=backfill.planLinkedInCadenceBackfill(org,input,day(14)).projected;const item=queue.linkedInOutreachQueue(org,projected,day(14),"followups").items[0];assert.ok(item);assert.equal(item.stage,"day14_insight");assert.equal(item.previousOutbound.message,"Actual earlier question");assert.equal(projected.growth_targets[0].first_outbound_at,first);});
test("tenant-specific fallback and stage intent contain no inherited sender facts",()=>{for(const [name,description] of [["A Clinic","grief counselling"],["B Practice","sports rehabilitation"]]){const profile={business:{name,description}};const text=cadence.contextualOutreachDraft({target_name:"Person",stage:"day28_relevance",previous_outbound_text:"Actual question"},profile);assert.match(text,new RegExp(description));assert.doesNotMatch(text,/Root|David|workplace wellbeing|brochure/);assert.doesNotMatch(text,new RegExp(name==="A Clinic"?"sports rehabilitation":"grief counselling"));}assert.equal(cadence.contextualOutreachDraft({target_name:"Person",stage:"day3_followup"},{business:{}}),"");});
test("confirmed final close plans parked exactly once",()=>{const projected=backfill.planLinkedInCadenceBackfill(org,fixture(),day(42)).projected;const plan=governor.planManualCompletion(org,projected,"growth_targets","target");assert.equal(plan.allowed,true);assert.equal(plan.patch.stage,"parked");assert.equal(plan.patch.status,"parked");assert.equal(cadence.nextGrowthStage("day42_close"),"parked");});
test("backfill is tenant isolated and second dry run is idempotent",()=>{const input=fixture();input.growth_targets.push({...input.growth_targets[0],id:"foreign",organisation_id:"tenant-b"});const firstRun=backfill.planLinkedInCadenceBackfill(org,input,day(28));assert.equal(firstRun.repairs.length,1);assert.equal(firstRun.projected.growth_targets[1].stage,"day3_dm");assert.equal(backfill.planLinkedInCadenceBackfill(org,firstRun.projected,day(28)).repairs.length,0);});

test("missing targets are planned for one-time creation without phantom actionable ids",()=>{const input=fixture();input.growth_targets=[];const result=backfill.planLinkedInCadenceBackfill(org,input,day(28));assert.equal(result.repairs[0].id,null);assert.equal(result.repairs[0].patch.stage,"day28_relevance");assert.equal(result.repairs[0].patch.first_outbound_at,first);assert.equal(result.projected.growth_targets.length,0);});
test("a stored stage alone never fabricates intermediate sends or advances the evidence floor",()=>{const input=fixture();input.growth_targets[0].stage="day42_close";const result=backfill.planLinkedInCadenceBackfill(org,input,day(3));assert.equal(result.projected.growth_targets[0].stage,"day3_followup");assert.equal(result.projected.growth_targets[0].manual_completion.stage,"connection");});
