import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import * as React from 'react';
import * as jsx from 'react/jsx-runtime';
import {create,act} from 'react-test-renderer';
import {PGlite} from '@electric-sql/pglite';
const require=createRequire(import.meta.url);globalThis.IS_REACT_ACT_ENVIRONMENT=true;
function load(file,mocks={},globals={}){const loadedModule={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{module:loadedModule,exports:loadedModule.exports,URL,URLSearchParams,AbortSignal,Date,AbortController,console,...globals,require:n=>n in mocks?mocks[n]:n.startsWith('@/lib/')?load(n.replace('@/','')+'.ts',mocks,globals):n==='./PersonalAcquisition'?{__esModule:true,default:()=>null}:n.startsWith('./')?load(path.join(path.dirname(file),n+'.tsx'),mocks,globals):require(n)});return loadedModule.exports;}
const workflow=load('lib/acquisitionWorkflow.ts');
const helpers=load('lib/personalSignal.ts',{'@/lib/acquisitionWorkflow':workflow});
const org='78fa2ac8-e7b6-4b9b-9604-035723ece6b1',id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',actor='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const sample=(more={})=>({id,source_engine:'root_health_personal',source_record_id:'social:verified-123',record_type:'social_opportunity',status:'new',source_url:'https://www.linkedin.com/posts/root-discussion-123',reason:'Public discussion asking about routines and switching off.',signal:'Stress / sleep',metadata:{engine_safety:{public_context:true,consumer_outreach:false,health_targeting:false,verified_direct_discussion:true},original_post:'  I struggle to switch off after work. How do you relax? 👋\n',prepared_reply:'What helps you draw a boundary between the workday and your evening?'},acquisition_item_events:[],...more});
test('verified Personal Signal uses exact original text and public response, with no invented post from evidence',()=>{const item=sample(),signal=helpers.personalSignal(item);assert.equal(signal.platform,'LinkedIn');assert.equal(signal.original,item.metadata.original_post);assert.equal(signal.reply,item.metadata.prepared_reply);assert.equal(helpers.personalSignal(sample({metadata:{...item.metadata,original_post:null},evidence:'generic research'})),null);});
test('normal, Partner, search-demand/article and unsafe/unverified source records do not qualify',()=>{
 for(const item of [sample({source_engine:'other'}),sample({record_type:'partner_opportunity'}),sample({record_type:'b2b_lead'}),sample({source_url:'https://www.reddit.com/search/?q=stress'}),sample({source_url:'https://example.com/posts/stress'}),sample({source_url:'http://reddit.com/r/test/comments/id'}),sample({metadata:{...sample().metadata,lane:'Search Demand'}}),sample({metadata:{...sample().metadata,opportunity_type:'article'}}),sample({engine_state:{opportunity_type:'search_demand'}}),sample({engine_state:{opportunity_type:'article'}}),sample({metadata:{...sample().metadata,engine_safety:{...sample().metadata.engine_safety,verified_direct_discussion:false}}}),sample({metadata:{...sample().metadata,engine_safety:{...sample().metadata.engine_safety,consumer_outreach:true}}})])assert.equal(helpers.personalSignal(item),null);
});
test('explicit funnel uses existing statuses and named milestones, rejects skipped/unconfirmed steps and partners',()=>{
 let item=sample();for(const [action,status,label] of [['personal_responded','actioned','Responded'],['personal_engaged','engaged','Engaged'],['personal_capacity_check','engaged','Capacity Check'],['personal_signup','engaged','Signup'],['personal_subscriber','converted','Subscriber']]){assert.throws(()=>helpers.planPersonalSignalAction(item,action,false),/Explicitly/);const plan=helpers.planPersonalSignalAction(item,action,true);assert.equal(plan.nextStatus,status);assert.equal(plan.outcome,label);item={...item,status,acquisition_item_events:[...item.acquisition_item_events,{action,created_at:'2026-10-09T12:00:00Z'}]};assert.equal(helpers.personalFunnel(item),label);}
 assert.throws(()=>helpers.planPersonalSignalAction(sample({status:'engaged'}),'personal_signup',true),/preceding/);assert.throws(()=>helpers.planPersonalSignalAction(sample({record_type:'partner_opportunity'}),'personal_responded',true),/not a verified/);
});
async function cardFixture({popup=true,clipboard=true,status='new',events=[],request}={}){const requests=[],copies=[],opened=[];const item=sample({status,acquisition_item_events:events});let refreshed=0;const Card=load('app/dashboard/growth/acquisition/PersonalSignalCard.tsx',{react:React,'react/jsx-runtime':jsx},{crypto:{randomUUID:()=>id},window:{open:(url,target)=>{opened.push([url,target]);return popup?{opener:{},location:{replace:url=>opened.push([url])}}:null;}},navigator:{clipboard:{writeText:async t=>{if(!clipboard)throw Error('blocked');copies.push(t);}}},fetch:async(url,init)=>{requests.push({url,body:JSON.parse(init.body)});return request?request():{ok:true,json:async()=>({success:true})};}}).default;let renderer;await act(async()=>{renderer=create(React.createElement(Card,{item,signal:helpers.personalSignal(item),organisationId:org,onSaved:async()=>refreshed++,onDismiss:()=>{}}));});const button=name=>renderer.root.findAllByType('button').find(n=>n.children.join('')===name);return {renderer,button,requests,copies,opened,refreshed:()=>refreshed,close:()=>act(async()=>renderer.unmount())};}
test('Copy and Open copy only the AI response; no funnel request; popup-safe new tab',async()=>{const f=await cardFixture();await act(async()=>f.button('Copy current text').props.onClick());await act(async()=>f.button('Open post & copy').props.onClick());assert.deepEqual(f.copies,[sample().metadata.prepared_reply,sample().metadata.prepared_reply]);assert.equal(f.requests.length,0);assert.deepEqual(f.opened,[['about:blank','_blank'],[helpers.personalSignal(sample()).url]]);await f.close();});
test('blocked popup still copies, clipboard failure leaves manual fallback, neither changes funnel',async()=>{for(const options of [{popup:false},{clipboard:false}]){const f=await cardFixture(options);await act(async()=>f.button('Open post & copy').props.onClick());assert.equal(f.requests.length,0);assert.match(f.renderer.root.findByProps({role:'status'}).children.join(''),options.popup===false?/Response copied.*popup was blocked/:/copy.*manually/);if(options.popup===false)assert.equal(f.copies.length,1);await f.close();}});
test('Responded is disabled until human confirmation and posts once to existing endpoint',async()=>{let resolve;const waiting=new Promise(r=>resolve=r);const f=await cardFixture({request:()=>waiting});assert.equal(f.button('Mark responded').props.disabled,true);await act(async()=>f.renderer.root.findByType('input').props.onChange({target:{checked:true}}));const click=f.button('Mark responded').props.onClick;await act(async()=>{click();click();});assert.equal(f.requests.length,1);assert.equal(f.requests[0].body.action,'personal_responded');assert.equal(f.requests[0].body.confirmed,true);assert.equal(f.requests[0].body.organisationId,org);await act(async()=>resolve({ok:true,json:async()=>({success:true})}));assert.equal(f.refreshed(),1);await f.close();});
test('later milestone buttons submit the correct explicit acquisition events',async()=>{for(const [status,events,label,action] of [['actioned',[],'Engaged','personal_engaged'],['engaged',[],'Capacity Check','personal_capacity_check'],['engaged',[{action:'personal_capacity_check',created_at:'2026-10-09'}],'Signup','personal_signup'],['engaged',[{action:'personal_signup',created_at:'2026-10-09'}],'Subscriber','personal_subscriber']]){const f=await cardFixture({status,events});await act(async()=>f.renderer.root.findByType('input').props.onChange({target:{checked:true}}));await act(async()=>f.button(label).props.onClick());assert.equal(f.requests[0].body.action,action);await f.close();}});
test('existing Acquisition page renders Personal Signal in normal queue and leaves other cards and filters intact',async()=>{
 const items=[sample(),sample({id:'normal',source_engine:'other',record_type:'personal_opportunity',entity:'Normal opportunity'}),sample({id:'partner',record_type:'partner_opportunity',entity:'Partner opportunity'})];
 const Page=load('app/dashboard/growth/acquisition/page.tsx',{react:React,'react/jsx-runtime':jsx,'./PartnerConversation':{__esModule:true,default:()=>null},'./ManualOpportunity':{__esModule:true,default:()=>null}},{window:{location:{href:'https://ops.example/dashboard/growth/acquisition?record_type=personal_opportunity',search:'?record_type=personal_opportunity'}},fetch:async url=>({ok:true,json:async()=>url.startsWith('/api/org/current')?{organisationId:org}:{items,total:3}})}).default;let renderer;await act(async()=>{renderer=create(React.createElement(Page));});const text=JSON.stringify(renderer.toJSON());assert.match(text,/Original post/);assert.match(text,/Response/);assert.match(text,/Normal opportunity/);assert.match(text,/Partner opportunity/);assert.equal(renderer.root.findAllByType('select')[0].props.value,'personal_opportunity');assert.equal(renderer.root.findAllByType('article').length,3);await act(async()=>renderer.unmount());
});
test('existing SQL RPC persists all Personal events with actor, status and audit history using the additive migration; existing handoffs remain intact',async()=>{
 const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create table organisations(id uuid primary key);insert into organisations values('${org}');`);for(const name of ['20260923140000_acquisition_ingestion.sql','20260924100000_actionable_acquisition_queue.sql','20260927100000_acquisition_handoff.sql','20260925100000_acquisition_engine_state.sql','20261009170000_personal_signal_acquisition_actions.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));await db.query("insert into acquisition_items(id,organisation_id,source_engine,source_record_id,record_type,source_url,metadata) values($1,$2,'root_health_personal','social:1','social_opportunity',$3,$4)",[id,org,sample().source_url,JSON.stringify(sample().metadata)]);let item=sample();let count=0;for(const action of helpers.personalSignalActions){const plan=helpers.planPersonalSignalAction(item,action,true);const key=`00000000-0000-4000-8000-${String(++count).padStart(12,'0')}`;const args=[org,id,actor,item.status,action,plan.nextStatus,plan.outcome,'Explicit manual confirmation',key,plan.marksActioned];const sql='select status from apply_acquisition_action($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)';assert.equal((await db.query(sql,args)).rows[0].status,plan.nextStatus);await db.query(sql,args);item={...item,status:plan.nextStatus,acquisition_item_events:[...item.acquisition_item_events,{action,created_at:'2026-10-09'}]};}const events=(await db.query('select action,actor_user_id from acquisition_item_events order by created_at')).rows;assert.equal(events.length,5);assert.ok(events.every(e=>e.actor_user_id===actor));
 const legacy='cccccccc-cccc-4ccc-8ccc-cccccccccccc';await db.query("insert into acquisition_items(id,organisation_id,source_engine,source_record_id,record_type,status) values($1,$2,'legacy','normal','personal_opportunity','accepted')",[legacy,org]);
 await assert.rejects(db.query("select * from apply_acquisition_action($1,$2,$3,'accepted','mark_actioned','actioned',null,null,$4,true)",[org,legacy,actor,'dddddddd-dddd-4ddd-8ddd-dddddddddddd']),/handoff_required/);
 assert.equal((await db.query("select status from apply_acquisition_action($1,$2,$3,'accepted','create_content_draft','actioned',null,null,$4,true)",[org,legacy,actor,'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'])).rows[0].status,'actioned');
 await assert.rejects(db.query("select * from apply_acquisition_action($1,$2,$3,'actioned','personal_engaged','engaged','Engaged',null,$4,false)",[org,legacy,actor,'ffffffff-ffff-4fff-8fff-ffffffffffff']),/unverified_personal_signal/);
 }finally{await db.close();}
});

test('Personal action API requires tenant write access, verified evidence and explicit confirmation; retries do not duplicate events',async()=>{
 for(const scenario of ['success','unconfirmed','partner','unverified','foreign','duplicate','content']){
 const calls=[];let item=sample({organisation_id:org});if(scenario==='partner')item=sample({record_type:'partner_opportunity',organisation_id:org});if(scenario==='unverified')item=sample({metadata:{...sample().metadata,engine_safety:{}},organisation_id:org});if(scenario==='duplicate')item={...item,status:'actioned',acquisition_item_events:[{action:'personal_responded',created_at:'2026-10-09',idempotency_key:id}]};
 if(scenario==='content')item={...item,source_url:'https://reddit.com/r/test/comments/id',metadata:{...item.metadata,action_type:'CONTENT_SIGNAL'}};
 const filters={};const db={from:()=>{const q={select:()=>q,eq:(k,v)=>{filters[k]=v;return q;},maybeSingle:async()=>({data:scenario==='foreign'?null:item})};return q;},rpc:async(name,args)=>{calls.push({name,args});return {data:[{...item,status:args.p_new_status}]};}};
 const route=load('app/api/growth/acquisition/[id]/action/route.ts',{'next/server':{NextResponse:{json:(body,opts={})=>({body,status:opts.status||200})}},'@/lib/tenantAuth':{requireOrganisation:async(o,write)=>{assert.equal(o,org);assert.equal(write,true);return {organisationId:org,userId:actor};},accessErrorResponse:()=>null},'@/lib/supabaseAdmin':{supabaseAdmin:db},'@/lib/growthIngestion.server':{uuid:/^[0-9a-f-]{36}$/i},'@/lib/acquisitionPromotion.server':{promoteAcquisition:()=>assert.fail('No outreach promotion')},'@/lib/acquisitionWorkflow':workflow,'@/lib/personalSignal':helpers});
 const result=await route.POST({json:async()=>({organisationId:org,idempotencyKey:id,action:'personal_responded',confirmed:scenario!=='unconfirmed'})},{params:Promise.resolve({id})});
 assert.equal(filters.organisation_id,org);assert.equal(result.status,['success','duplicate'].includes(scenario)?200:scenario==='foreign'?404:400);assert.equal(calls.length,scenario==='success'?1:0);
 if(scenario==='success'){assert.equal(calls[0].name,'apply_acquisition_action');assert.equal(calls[0].args.p_actor_user_id,actor);assert.equal(calls[0].args.p_new_status,'actioned');assert.equal(calls[0].args.p_marks_actioned,true);}if(scenario==='duplicate')assert.equal(result.body.duplicate,true);
 }
});

test('existing engine-state ingestion retains original post, public reply and verified safety for the Personal card',()=>{const item=sample();const parser=load('lib/engineStateIngestion.server.ts');const record={...item,status:'new',metadata:{original_post:item.metadata.original_post,prepared_reply:item.metadata.prepared_reply},safety:item.metadata.engine_safety,observed_at:'2026-10-09T12:00:00Z',state:{status:'new',channel:'reddit',opportunity_type:'public_question'}};const parsed=parser.parseEngineStateBatch({organisation_id:org,records:[record]},Date.parse('2026-10-09T12:01:00Z')).records[0];assert.equal(helpers.personalSignal(parsed).original,item.metadata.original_post);assert.equal(helpers.personalSignal(parsed).reply,item.metadata.prepared_reply);});


test('service-role RPC independently rejects research provenance and non-discussion HTTPS URLs despite supplied safety flags',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create table organisations(id uuid primary key);insert into organisations values('${org}');`);
 for(const name of ['20260923140000_acquisition_ingestion.sql','20260924100000_actionable_acquisition_queue.sql','20260927100000_acquisition_handoff.sql','20260925100000_acquisition_engine_state.sql','20261009170000_personal_signal_acquisition_actions.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 const validUrls=[sample().source_url,'https://old.reddit.com/r/test/comments/123/topic','https://m.facebook.com/user/posts/123','https://facebook.com/story.php?story_fbid=123&id=456','https://instagram.com/p/123/','https://instagram.com/reel/123/','https://threads.net/@user/post/123','https://threads.com/@user/post/123','https://x.com/user/status/123','https://twitter.com/user/status/123','https://linkedin.com/posts/user-123','https://linkedin.com/feed/update/urn:li:activity:123','https://tiktok.com/@user/video/123'];
 const rejected=[...['https://example.com/article/stress','https://reddit.com/search/?q=stress','https://reddit.com/?next=/comments/123','https://reddit.com.evil.test/comments/123','https://user@reddit.com/comments/123','https://reddit.com:8443/comments/123','https://instagram.com/blog/123','https://facebook.com/story.php?story_fbid=','http://x.com/user/status/123'].map(source_url=>({source_url})),
 ...['lane','opportunity_type','content_type','sheet_tab'].flatMap(field=>['Search Demand','article','blog','Partner','referrer'].map(value=>({metadata:{...sample().metadata,[field]:value}}))),
 ...['search_demand','article','blog','partner','referral'].map(opportunity_type=>({engine_state:{opportunity_type}})),
 ...['public_context','consumer_outreach','health_targeting','verified_direct_discussion'].map(key=>({metadata:{...sample().metadata,engine_safety:{...sample().metadata.engine_safety,[key]:!sample().metadata.engine_safety[key]}}})),{metadata:{...sample().metadata,original_post:''}}];
 let index=0;
 for(const [accepted,records] of [[true,validUrls.map(source_url=>({source_url}))],[false,rejected]])for(const overrides of records){
 const item=sample(overrides),itemId=`00000000-0000-4000-8000-${String(++index).padStart(12,'0')}`;
 await db.query("insert into acquisition_items(id,organisation_id,source_engine,source_record_id,record_type,source_url,metadata,engine_state) values($1,$2,'root_health_personal',$3,'social_opportunity',$4,$5,$6)",[itemId,org,'sql:'+index,item.source_url,JSON.stringify(item.metadata),item.engine_state?JSON.stringify(item.engine_state):null]);
 await db.exec('set role service_role');
 const call=()=>db.query("select status from apply_acquisition_action($1,$2,$3,'new','personal_responded','actioned','Responded',null,$4,true)",[org,itemId,actor,itemId]);
 try{if(accepted)assert.equal((await call()).rows[0].status,'actioned');else await assert.rejects(call(),/unverified_personal_signal/,JSON.stringify(overrides));}finally{await db.exec('reset role');}
 if(!accepted){assert.equal((await db.query('select status from acquisition_items where id=$1',[itemId])).rows[0].status,'new');assert.equal((await db.query('select count(*)::int as count from acquisition_item_events where acquisition_item_id=$1',[itemId])).rows[0].count,0);}
 }
 }finally{await db.close();}
});

test('platform routing never treats public availability as response permission',()=>{
 const reddit=sample({source_url:'https://reddit.com/r/test/comments/id',metadata:{...sample().metadata,action_type:'PUBLIC_RESPONSE',content_angle:'Workday boundaries',content_asset_type:'LinkedIn post'}});
 assert.equal(helpers.personalSignal(reddit),null);assert.equal(helpers.contentSignal(reddit).reply,null);assert.equal(helpers.contentSignal(reddit).original,reddit.metadata.original_post);
 for(const action of ['route_responses','mark_engaged','mark_converted',...helpers.personalSignalActions])assert.equal(helpers.personalSocialActionAllowed(reddit,action),false);
 assert.equal(helpers.personalSocialActionAllowed(reddit,'create_content_draft'),true);
 assert.ok(helpers.personalSignal(sample()));
 for(const url of ['https://facebook.com/user/posts/id','https://instagram.com/p/id','https://x.com/user/status/id','https://tiktok.com/@user/video/id','https://threads.net/@user/post/id']) {
  const item=sample({source_url:url});assert.equal(helpers.personalSocialActionType(item),'CONTENT_SIGNAL');
  assert.equal(helpers.personalSocialActionType({...item,metadata:{...item.metadata,action_type:'PUBLIC_RESPONSE',public_engagement_surface_verified:true}}),'CONTENT_SIGNAL');
  assert.equal(helpers.personalSocialActionType({...item,metadata:{...item.metadata,action_type:'PUBLIC_RESPONSE',public_engagement_surface_verified:true,public_engagement_surface_evidence:'Owned Root public engagement surface confirmed'}}),'PUBLIC_RESPONSE');
 }
 assert.equal(helpers.contentSignal(sample({metadata:{...sample().metadata,action_type:'CONTENT_SIGNAL',original_post:'I want to kill myself'}})),null);
});
