import { NextResponse } from "next/server";
import { accessErrorResponse } from "@/lib/tenantAuth";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { requireFounderIntelligence } from "@/lib/founderIntelligenceAuth.server";
import { founderLaneLabel,founderPromotionDefault,parseFounderGeography,parseFounderLane,type FounderDeepResearch } from "@/lib/founderIntelligence";
import { founderContextForAcquisition } from "@/lib/founderIntelligence.server";
import { parseIngestion } from "@/lib/growthIngestion.server";
export const runtime="nodejs";
export async function POST(req:Request){try{const body=await req.json().catch(()=>({})),tenant=await requireFounderIntelligence(body.organisationId),lane=parseFounderLane(body.lane),research=body.research&&typeof body.research==="object"?body.research as FounderDeepResearch:null;if(!research||!String(research.name||"").trim())throw Error("Research an organisation before sending it to Acquisition.");research.lane=lane;research.geography=parseFounderGeography(body.geography??research.geography);const recordType=String(body.recordType||founderPromotionDefault(lane)||"");if(!["partner_opportunity","b2b_lead"].includes(recordType))throw Error("Choose Partner opportunity or B2B lead.");const website=/^https?:\/\//i.test(String(research.website||""))?String(research.website):null,sourceRecordId=`founder:${lane}:${String(research.name).trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,120)}`,evidence=founderContextForAcquisition(research),{records}=parseIngestion({organisation_id:tenant.organisationId,records:[{source_engine:"founder_intelligence",source_record_id:sourceRecordId,record_type:recordType,status:"new",entity:String(research.name).trim(),company:String(research.name).trim(),source_url:website||research.sourceUrls?.[0]||null,evidence,reason:String((lane==="workplace_buyers"?research.organisationalFit:research.strategicFit)||"").slice(0,5000)||null,signal:Array.isArray(research.currentSignals)?research.currentSignals.join("\n").slice(0,5000):null,suggested_action:String(research.recommendedApproach||"Review Founder Intelligence and choose next action.").slice(0,3000),metadata:{founder_intelligence:research,founder_lane:lane,founder_lane_label:founderLaneLabel(lane),created_by:tenant.userId,public_context_confirmed:true}}]}),record=records[0];const {data,error}=await supabaseAdmin.from("acquisition_items").upsert(record,{onConflict:"organisation_id,source_engine,source_record_id",ignoreDuplicates:true}).select("id").maybeSingle();if(error)throw error;let id=data?.id,duplicate=false;if(!id){duplicate=true;const {data:existing,error:lookupError}=await supabaseAdmin.from("acquisition_items").select("id").eq("organisation_id",tenant.organisationId).eq("source_engine","founder_intelligence").eq("source_record_id",sourceRecordId).maybeSingle();if(lookupError||!existing?.id)throw Error("Unable to verify Founder Intelligence promotion.");id=existing.id;}return NextResponse.json({success:true,id,duplicate,destination:`/dashboard/growth/acquisition?${new URLSearchParams({organisationId:tenant.organisationId,itemId:id})}`});}catch(error){return accessErrorResponse(error)||NextResponse.json({success:false,error:error instanceof Error?error.message:"Unable to send opportunity to Acquisition."},{status:400});}}
