import { assessConnectionCapabilities, channelCatalog } from "@/lib/channelCapabilities";

export type SetupState = "ready_to_connect" | "permissions_incomplete" | "developer_registration_required" | "credentials_required" | "business_verification_required" | "provider_approval_required" | "paid_account_required" | "partially_operational" | "manual_only" | "unsupported";
export const setupLabels: Record<SetupState, string> = {
  ready_to_connect: "Ready to connect", permissions_incomplete: "Connected; permissions incomplete or unverified",
  developer_registration_required: "Provider app registration required", credentials_required: "Operator setup required",
  business_verification_required: "Provider business verification required", provider_approval_required: "Provider approval required",
  paid_account_required: "Provider account upgrade required", partially_operational: "Connected; only partially operational",
  manual_only: "Manual workflow / automation unavailable", unsupported: "Not supported in Ops yet",
};
type Guide = { providerUrl: string; customerStep: string; operatorStep: string; limitation: string; approval: string; scopes: string; missing: string; callback: string };
export const providerGuides: Record<string, Guide> = {
  facebook: { providerUrl: "https://www.facebook.com/", customerStep: "Sign in with the account that manages your Page, select the Page and approve the requested access.", operatorStep: "Root configures the Meta app, callback and credentials, and completes required app review/business verification for customer use.", limitation: "Comment reading/replies are not permission-verified. Use the Page on Facebook until verified.", approval: "Meta review and applicable business verification; actual approval is not recorded.", scopes: "pages_show_list, pages_read_engagement, pages_manage_posts, business_management, instagram_basic, instagram_content_publish", missing: "pages_read_user_content / pages_manage_engagement are not requested by the current flow.", callback: "/api/oauth/facebook/callback" },
  instagram: { providerUrl: "https://www.instagram.com/", customerStep: "Use a professional Instagram account linked to the Facebook Page you manage. Connect through Facebook and select the correct Page.", operatorStep: "Root configures the shared Meta app and required review. You do not need to create your own developer app.", limitation: "Comment reading/replies remain unverified; use Instagram for those actions.", approval: "Meta review and applicable verification; actual approval is not recorded.", scopes: "Shared Facebook flow: instagram_basic, instagram_content_publish plus Page permissions", missing: "instagram_manage_comments is not requested by the current flow.", callback: "/api/oauth/facebook/callback" },
  linkedin: { providerUrl: "https://www.linkedin.com/", customerStep: "Connect the LinkedIn member account you want to publish from and approve the requested access.", operatorStep: "Root maintains the developer app and approved products. Additional Community Management access requires provider approval and an enabled implementation.", limitation: "Activity reading remains runtime-disabled. Invitations and messages remain manual; reconnecting does not enable them.", approval: "Additional products require LinkedIn approval; current approval status is unverified.", scopes: "openid, profile, email, w_member_social", missing: "Additional reading access is not enabled; no messaging or invitation adapter.", callback: "/api/oauth/linkedin/callback" },
  threads: { providerUrl: "https://www.threads.net/", customerStep: "Connect your Threads account and approve access for publishing.", operatorStep: "Root registers/configures the Threads app and handles provider review for customer accounts.", limitation: "Publishing adapter exists; comment reading and replies are not implemented.", approval: "Provider review for broader customer access must be confirmed by the app operator.", scopes: "threads_basic, threads_content_publish", missing: "No response/reply adapter; extra permissions alone will not add it.", callback: "/api/oauth/threads/callback" },
  tiktok: { providerUrl: "https://www.tiktok.com/", customerStep: "Connect TikTok with video.publish for Direct Post. Review creator-supported privacy and interaction settings before posting.", operatorStep: "Root registers/configures the developer app and Content Posting product and obtains required approval.", limitation: "Direct Post depends on the granted token, creator settings and app audit. Draft upload requires explicit selection; comment replies are not implemented.", approval: "Creator info verifies current Direct Post access. Unaudited clients may require a private account and Only me privacy.", scopes: "user.info.basic, video.upload, video.publish", missing: "Older tokens may lack video.publish and need reconnecting. Requested scopes alone do not prove a grant.", callback: "/api/oauth/tiktok/callback" },
  google: { providerUrl: "https://business.google.com/", customerStep: "Use Google Business Profile directly for posts and reviews. Connecting here stores identity only.", operatorStep: "Root must obtain Business Profile API access, configure the Cloud project and implement supported business actions before customer activation.", limitation: "Identity OAuth cannot publish, read reviews or reply to reviews in Ops.", approval: "Business Profile API access approval and an eligible managed business are required for future activation.", scopes: "openid, userinfo.profile, userinfo.email", missing: "business.manage is not requested; business adapters are absent.", callback: "/api/oauth/google/callback" },
  email: { providerUrl: "https://mail.google.com/", customerStep: "Ask your workspace operator to finish the Gmail engine connection. Authorize Google in the existing engine when requested; approve each Ops reply before sending.", operatorStep: "Root configures the tenant-scoped B2B endpoint and ingestion secret and verifies engine authorization and delivery outcomes. Never ask customers to paste engine secrets here.", limitation: "Saved engine configuration does not prove reachability, Gmail read/send authorization or delivery.", approval: "Google verification depends on the engine's sensitive/restricted scopes and deployment. Operator must verify it.", scopes: "Gmail authorization is owned by the existing engine, not the Google identity OAuth flow in Ops.", missing: "Live engine authorization/read/send verification is not available from this stored-state check.", callback: "Managed in the existing Google engine; no Ops Gmail OAuth callback." },
};
/** Setup is presentation around existing capabilities, never permission or execution authority. */
export function buildProviderSetup(platform: string, credential: string, configured: boolean | null) {
  const guide = providerGuides[platform];
  const channel = channelCatalog.find(c => c.id === platform);
  const connected = credential === "connected";
  const assessment = assessConnectionCapabilities(platform, credential);
  const state: SetupState = !guide ? platform === "crm" ? "manual_only" : "unsupported"
    : platform === "google" ? "manual_only" : platform === "email" ? connected ? "permissions_incomplete" : "credentials_required"
    : configured !== true ? "credentials_required" : connected ? "permissions_incomplete" : "ready_to_connect";
  return { state, label: setupLabels[state], canConnect: !!guide && !!channel?.connectPath && configured === true,
    configuration: configured === null ? "unknown" : configured ? "present_not_verified" : "incomplete",
    credentialOwner: platform === "email" ? "Tenant-scoped engine configuration, managed by Root" : guide ? "Root-wide OAuth app; workspace-scoped connected account" : "No self-service credentials collected",
    connected: connected ? platform === "email" ? "Engine configuration present" : "Account credential saved" : ["expired", "reconnect_required"].includes(credential) ? "Saved connection needs reconnect" : "No connected account reported",
    customerStep: guide?.customerStep || (platform === "crm" ? "Ask your operator to configure existing authenticated acquisition ingestion." : "Use the native service. Ops does not currently connect this channel."),
    operatorStep: guide?.operatorStep || "No new developer registration or purchase is requested for an unimplemented connector.",
    limitation: guide?.limitation || "No self-service operational channel adapter is enabled.",
    approval: guide?.approval || "Not assessed for this unimplemented connector.",
    payment: "No paid upgrade is established by this check. Confirm account eligibility with the provider; payment cannot unlock an absent adapter.",
    providerUrl: guide?.providerUrl || null, scopes: guide?.scopes || "Not implemented", missing: guide?.missing || "Adapter unavailable",
    callback: guide?.callback || null, fallback: assessment.manualFallback,
    recheck: "Recheck reloads workspace credentials, recorded expiry, operator configuration and capability restrictions. It does not send, publish or verify remote grants/delivery. Unverified capabilities stay unverified.",
  };
}
export type ProviderSetup = ReturnType<typeof buildProviderSetup>;
